---
kind: pipeline
type: docker
name: default

workspace:
  base: /drone/src

steps:

  - name: build
    image: nextcloudci/android:android-54
    depends_on: [ clone ] 
    environment:
      JVM_OPTS: -Xmx3200m
      ENCODED_KEYSTORE:
        from_secret: ENCODED_KEYSTORE
      KEYSTORE_PASSWORD:
        from_secret: KEYSTORE_PASSWORD
      KEY_ALIAS:
        from_secret: KEY_ALIAS
      KEY_PASSWORD:
        from_secret: KEY_PASSWORD
      KEYSTORE:
        from_secret: KEYSTORE
    commands:
      - cd app
      - echo $ENCODED_KEYSTORE | base64 --decode > /drone/src/app/release.pfk
      - ./gradlew clean assembleRelease --no-daemon --stacktrace