---
kind: pipeline
type: docker
name: default

steps:
  - name: run-tests
    # alternative images: nextcloudci/android:androidBase-4 nextcloudci/android:android-54 circleci/android:api-30
    image: nextcloudci/android:android-54
    depends_on: [ clone ]
    commands:
      - cd app
      #if permission for Gradlew Dependencies fail, use this.
      # - sudo chmod +x ./gradlew
      - ./gradlew lint test --stacktrace

  - name: build
    image: nextcloudci/android:android-54
    depends_on: [ run-tests ] 
    environment:
      JVM_OPTS: -Xmx3200m
    commands:
      - echo $ENCODED_KEYSTORE | base64 --decode > ~/unchained-android/app/release.pfk
      - echo 'export KEYSTORE=~/unchained-android/app/release.pfk' >> $BASH_ENV
      - ./gradlew clean assembleRelease --no-daemon --stacktrace