---
kind: pipeline
type: docker
name: tests

workspace:
  base: /drone/src/app

steps:
  - name: run tests
    image: circleci/android:api-30
    depends_on: [ clone ] 
    commands:
      - echo $PWD
      - ls
      - ./gradlew lint test

  - name: build
    image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    commands:
      - echo $ENCODED_KEYSTORE | base64 --decode > ~/unchained-android/app/release.pfk
      - echo 'export KEYSTORE=~/unchained-android/app/release.pfk' >> $BASH_ENV
      - ./gradlew clean assembleRelease --no-daemon --stacktrace