---
kind: pipeline
type: docker
name: default

workspace:
  base: /drone/src

steps:
  - name: build
    image: nextcloudci/android:android-54
    depends_on: [ clone ] 
    environment:
      JVM_OPTS: -Xmx3200m
      KEYSTORE: /drone/src/app/release.pfk
    commands:
      - echo $BASH_ENV
      - cd app
      - echo $PWD
      - ls
      - echo $ENCODED_KEYSTORE | base64 --decode > ./release.pfk
      - ./gradlew clean assembleRelease --no-daemon --stacktrace