files:
  - source: /app/app/src/**/res/values/strings*.xml
    translation: /%original_path%-%two_letters_code%/%original_file_name%
    translate_attributes: 0
    content_segmentation: 0
  - source: /fastlane/metadata/android/en-US/*.txt
    ignore:
      - title.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
  - source: /fastlane/metadata/android/en-US/changelogs/*.txt
    translation: /fastlane/metadata/android/%locale%/changelogs/%original_file_name%
